### ISSUE TITLE
Spring Boot Embedded Tomcat NullPointerException get-serverName

### ISSUE THREAD

**Issue by sb-wnyffenegger** [akkinoc/logback-access-spring-boot-starter#96]
## Describe the bug

Running locally using an IDEA results in NullPointerExceptions when attempting to log. 

Spring Boot Dependencies: Spring Boot Starter Parent 2.6.0 with Tomcat

logback-access.xml
```
<configuration>
    <statusListener class="ch.qos.logback.core.status.OnConsoleStatusListener"/>

    <appender name="logstash-access" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="net.logstash.logback.encoder.LogstashAccessEncoder">
            <fieldNames>
                <requestHeaders>request_headers</requestHeaders>
                <responseHeaders>response_headers</responseHeaders>
                <requestedUrl>requested_url</requestedUrl>
                <statusCode>status_code</statusCode>
            </fieldNames>
            <requestHeaderFilter class="a.package.LogstashHeaderFilter">
                <exclude>Authorization</exclude>
            </requestHeaderFilter>
        </encoder>
    </appender>

    <appender-ref ref="logstash-access"/>
</configuration>
```

Log
```
09:49:00,681 |-ERROR in ch.qos.logback.core.ConsoleAppender[logstash-access] - Appender [logstash-access] failed to append. java.lang.NullPointerException: <get-serverName>(...) must not be null
	at java.lang.NullPointerException: <get-serverName>(...) must not be null
	at 	at dev.akkinoc.spring.boot.logback.access.tomcat.LogbackAccessTomcatEventSource.getServerName(LogbackAccessTomcatEventSource.kt:53)
	at 	at dev.akkinoc.spring.boot.logback.access.LogbackAccessEventSource$Fixed.<init>(LogbackAccessEventSource.kt:181)
	at 	at dev.akkinoc.spring.boot.logback.access.LogbackAccessEventSource.fix(LogbackAccessEventSource.kt:156)
	at 	at dev.akkinoc.spring.boot.logback.access.LogbackAccessEvent.prepareForDeferredProcessing(LogbackAccessEvent.kt:159)
```

## To Reproduce

* Create a default spring boot app with a hello controller
```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.0</version>
    </parent>
```
* Add the logback related dependencies
```
        <dependency>
            <groupId>net.logstash.logback</groupId>
            <artifactId>logstash-logback-encoder</artifactId>
            <version>${logback-encoder.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>
        <dependency>
            <groupId>dev.akkinoc.spring.boot</groupId>
            <artifactId>logback-access-spring-boot-starter</artifactId>
            <version>3.1.0</version>
        </dependency>
```
* Add the logback-access.xml file specified above
* Start up the application
* Hit the hello controller

## Expected behavior

Normal logging behavior to continue or for documentation to be available concerning upgrading the major version.

### Environment

* **Version of this library used**: 3.0.0 and 3.1.0
* **Version of Java used**: Java 11 and Java 17

**Comment by akkinoc** [comment]
Thank you for the report.

I couldn't reproduce it in my environment...
Would you please provide the following information?

* Minimum sample project that can reproduce this issue
* The hostname of the environment that can reproduce this issue
* HTTP request content (including header) that can reproduce this issue

**Comment by sb-wnyffenegger** [comment]
I haven't commented for awhile on this but I'll work next week on getting a reproduction of this issue to you.

**Comment by akkinoc** [comment]
This issue is inactive, so I close it.
If you still have problems, please open a new issue.

**Comment by theotherp** [comment]
I have the same problem, still in 4.3.2. I was unable to build a reproducer but you can easily test it with my project:

1. Clone https://github.com/theotherp/nzbhydra2/tree/spring335-logback-access.
2. Open and run `org.nzbhydra.NzbHydra` with the argument `directstart` (there's also an IntelliJ run config called `Run app`).
3. Set a breakpoint in the catch block of `ch.qos.logback.core.UnsynchronizedAppenderBase#doAppend`.
4. Open http://127.0.0.1:5076

It seems to be some kind of race condition. If I set a breakpoint in `org.apache.coyote.Request#serverName` which suspends all threads the logging works but without breakpoint when LogbackAccess calls the method the value doesn't exist yet.

Weirdly I don't even have to suspend for it to work:
![image](https://github.com/user-attachments/assets/00a85c9e-b1c0-443b-9531-caa96f12520e)
With this the calls are logged, with this breakpoint disabled it doesn't. Some kind of weird Heisenbug,
